name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  SST_TELEMETRY_DISABLED: "1"
  AWS_SDK_LOAD_CONFIG: "1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    # set workign directory
    defaults:
      run:
        working-directory: ./my-sst-app
    env:
      SST_STAGE: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::643476110649:role/github-ci-role
          aws-region: us-east-1
    # https://github.com/pnpm/action-setup
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.0
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Deploy
        run: pnpm run deploy